site_name: GradeBot Guru Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - Architecture: architecture.md
  - SRS: srs.md
  - ADRs:
      - Template: adr/adr_template.md
      - Example: adr/adr_001_example.md
      - Configuration Loader: adr/0001-configuration-loader.md
      - Logging Configuration: adr/0002-logging-configuration.md
      - Load Rubric: adr/0003-load-rubric.md
      - Submission Loader: adr/0004-submission-loader.md
      - Use Custom LLM Interface: adr/0005-use-custom-llm-interface.md
      - Base LLM Interface: adr/0006-base-llm-interface.md
      - OpenAI LLM Interface: adr/0007-openai-llm-interface.md
  - API:
      - Overview: api/overview.md
      - Configuration: api/config.md
      - Rubric Loader: api/rubric_loader.md
      - Submission Loader: api/submission_loader.md
      - Base LLM: api/base_llm.md
      - OpenAI LLM: api/openai_llm.md
  - Examples:
      - Rubrics: examples/rubrics.md
      - Submissions: examples/submissions.md
      - Prompts: examples/prompts.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - FAQ: faq.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true