site_name: GradeBot Guru Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - Architecture: architecture.md
  - SRS: srs.md
  - ADRs:
      - Template: adr/adr_template.md
      - Example: adr/adr_001_example.md
      - Configuration Loader: adr/0001-configuration-loader.md
      - Logging Configuration: adr/0002-logging-configuration.md
      - Load Rubric: adr/0003-load-rubric.md
      - Submission Loader: adr/0004-submission-loader.md
      - Use Custom LLM Interface: adr/0005-use-custom-llm-interface.md
      - Base LLM Interface: adr/0006-base-llm-interface.md
      - OpenAI LLM Interface: adr/0007-openai-llm-interface.md
      - LLM Factory: adr/0008-llm-factory.md
      - Build Process: adr/0009-build-process.md
      - Project Code Consistency: adr/0010-project-code-consistency.md
      - Improving Marking Consistency: adr/0011-improving-marking-consistency.md
      - Default Loaders: adr/0012-default-loaders.md
      - Function Based Approach: adr/0013-function-based-approach.md
      - LLM Interface: adr/0014-llm-interface.md
      - Semantic Versioning: adr/0015-semantic-versioning.md
      - Rubric Schema: adr/0016-rubric-schema.md
      - Categorised Commit Messages: adr/0017-categorised-commit-messages.md
  - API:
      - Overview: api/overview.md
      - Base LLM: api/base_llm.md
      - Configuration: api/config.md
      - Core: api/core.md
      - Factory: api/factory.md
      - Grader: api/grader.md
      - Local LLM: api/local_llm.md
      - Logging Config: api/logging_config.md
      - Main: api/main.md
      - OpenAI LLM: api/openai_llm.md
      - Prompts: api/prompts.md
      - Rubric Loader: api/rubric_loader.md
      - Submission Loader: api/submission_loader.md
      - Aggregation Strategies: api/aggregation_strategies.md
  - Examples:
      - Rubrics: examples/rubrics.md
      - Submissions: examples/submissions.md
      - Prompts: examples/prompts.md
  - Admin Scripts:
      - Release: admin_scripts/release.md
      - Upload Issues: admin_scripts/upload_issues.md
      - Generate Markdown: admin_scripts/generate_markdown.md    
  - Tests:
      - Overview: tests/overview.md
      - Test Base LLM: tests/test_base_llm.md
      - Test Config: tests/test_config.md
      - Test Core: tests/test_core.md
      - Test Factory: tests/test_llm_factory.md
      - Test Integration: tests/test_integration.md
      - Test Local LLM: tests/test_local_llm.md
      - Test Logging: tests/test_logging.md
      - Test Main: tests/test_main.md
      - test OpenAI LLM: tests/test_openai_llm.md
      - Test Prompts: tests/test_prompts.md
      - Test Response Parser: tests/test_response_parser.md
      - Test Rubric Loader: tests/test_rubric_loader.md
      - Test Submission Loader: tests/test_submission_loader.md
  - Project Management: project_management.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - FAQ: faq.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true