site_name: GradeBot Guru Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Architecture: architecture.md
  - SRS: srs.md
  - ADRs:
      - Template: adr/adr_template.md
      - Example: adr/adr_001_example.md
      - Configuration Loader: adr/0001-configuration-loader.md
      - Logging Configuration: adr/0002-logging-configuration.md
      - Load Rubric: adr/0003-load-rubric.md
      - Submission Loader: adr/0004-submission-loader.md
      - Base LLM Interface: adr/0005-base-llm-interface.md
  - API:
      - Overview: api/overview.md
  - Examples:
      - Rubrics: examples/rubrics.md
      - Submissions: examples/submissions.md
      - Prompts: examples/prompts.md
theme:
  name: material
